spring.profiles.active=local
spring.application.name=museo

# Configuracion para bases de datos H2 para pruebas
spring.datasource.url=jdbc:h2:mem:museodb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=xxxxxxxxxxxxxxx
spring.datasource.password=xxxxxxxxxxxxxxx
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
# Server Config
server.port=8000
# JWT Configuration
jwt.secret=xxxxxxxxxxxxxxx
jwt.expiration-ms=900000
jwt.refresh-expiration-ms=604800000
# Activation Account token configuration
activation.account.token.secret=xxxxxxxxxxxxxxx
# 30min
activation.account.token.expiration-ms=1800000
app.frontend.url=http://localhost:xxxx
