spring.application.name=museo

# Configuracion para bases de datos H2 para pruebas
spring.datasource.url=jdbc:h2:mem:museodb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

# GraphQL
spring.graphql.graphiql.enabled=true